# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpryoxMoviesWorld' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpryoxMoviesWorld
pod 'Kingfisher', '~> 7.0'
pod 'ReachabilitySwift'
  target 'SpryoxMoviesWorldTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpryoxMoviesWorldUITests' do
    # Pods for testing
  end

end
